version: '3.8'

services:
  did-web-system:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: did-web-system:latest
    container_name: did-web-system
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - did-network

networks:
  did-network:
    driver: bridge 