# 로컬 개발 환경 설정
# default.yml을 상속받아 로컬 환경에서 필요한 설정만 오버라이드

server:
  port: 3000
  host: localhost

database:
  type: sqlite
  path: ./data/database.sqlite
  initialize: true

logging:
  level: warn  # 로컬 환경에서는 필요한 경고 및 오류만 출력 